/*******************************************************************************

Smith.h

Glenn Smith (Dec 1971)

From

The Proximity Effect in Systems of
Parallel Conductors and Electrically
Small Multiturn Loop Antennas

deciphered from a Horible scanned copy and ported to C by

Brian Case KU7F (2017)
rush at winkey dot org

*******************************************************************************/

#ifndef SMITH_H
#define SMITH_H

/*
C FORTRAN~ IV PROGRAM FOR SOLUTION BY THE METHOD OF COLLOCATION
C
C
C THIS PROGRAM USES THE METHOD UF COLLCCATION TO SOLVE A SYSTEM OF EQUATIONS
C FOR THE COEFFICIENTS OF TRIGONOMETRIC SERIES. THE SERIES REPRESENT THE
C NORMALIZED SURFACE CURRENT DENSITY ON EACH WIRE IN A SYSTEM OF nWires EQUALLY
C SPACED, PARALLEL, PERFECTLY CONDUCTING WIRES. USING THIS CURRENT AN
C APPROXIMATE VALUE OF THE NORPALILED HIGH FREQUENCY RESISTANCE OF THE SYSTEM
C IS CALCULATED. THE NUMBER OF HARMONIC TERMS USED TO DESCRIBE THE CURRENT ON
C EACH WIRE IS nHarmonics. THE RATIO ca IS EQUIVALENT TO THE SPACING BETWEEN WIRE
C CENTERS DIVIDED BY THE WIRE DIAMETER. 
*/

double SmithParallelCollocation(
    int nWires,
    int nHarmonics,
    double dfWireDia,
    double dfWireSpacing
);

/*
C FORTRAN~ IV PROGRAM FOR SOLUTION BY THE METHOD OF LEAST SQUARES
C
C
C THIS PROGRAM USES THE METHOD OF LEAST SQUARES TO SOLVE A SYSTEM OF EQUATIONS
C FOR THE COEFFICIENTS OF TRIGONOMETRIC SERIES. THE SERIES REPRESENT THE
C NORMALIZED SURFACE CURRENT DENSITY ON EACH WIRE IN A SYSTEM OF nWires EQUALLY
C SPACED, PARALLEL, PERFECTLY CONDUCTING WIRES. USING THIS CURRENT AN
C APPROXIMATE VALUE OF THE NORPALILED HIGH FREQUENCY RESISTANCE OF THE SYSTEM
C IS CALCULATED. THE NUMBER OF HARMONIC TERMS USED TO DESCRIBE THE CURRENT ON
C EACH WIRE IS nHarmonics. THE RATIO ca IS EQUIVALENT TO THE SPACING BETWEEN WIRE
C CENTERS DIVIDED BY THE WIRE DIAMETER.
*/

double SmithParallelLeastSquares(
    int nWires,
    int nHarmonics,
    double dfWireDia,
    double dfWireSpacing
);

/*
FORTRAN IV PROGRAM FOR CALCULATING THE CURRENT DISTRIBUTIONS CAUSED
BY INTERCONNECTING WIRES IN THE EXPERIMERTAL MODEL.

THIS PROGRAM USES THE METHOD OF COLLOCATION T3 SOLVE A SYSTEM OF
EQUATIONS FOR THE COEFFICIENTS OF TRIGONOMETRIC SERIES. THE SERIES
REPRESENT THE NORNALIZED SURFACE CURRENT DENSITY ON EACH WIRE IN
SYSTEM OF NW WIRES. THE NUMBER OF HARMONIC TERMS USED TO DESCRIBE
THE CURRENT ON EACH WIRE IS NH. THE RATIO CA IS EQUIVALENT TO THE
SPACING BETWEEN WIRE CENTERS DIVIDED BY THE WIRE DIAMETER. THE
NORMALIZED DIMENSIONS CAH2 AND CHL2 ARE THE TUBE RADIUS DIVIDED BY
THE TUBE HALF HEIGHT AND THE TUBE HALF HEIGHT DIVIDED BY THE LENGTH
OF THE INTERCONNECTING WIRES.

note this is unfinished as all the parameters cannot be passed to the function
*/

double SmithMultiturnCollocation(
    int nTurns,
    int nHarmonics,
    double dfWireDia,
    double dfWireSpacing
);

#endif

